library(DBI)
library(RSQLite)
library(proto)
library(gsubfn)
library(sqldf)
library(tcltk)
library(dplyr)
f <- file("household_power_consumption.txt")
elec_consumption <- sqldf("select * from f where Date In ('1/2/2007','2/2/2007')", dbname = tempfile(), file.format = list(header = T, row.names = F, sep=";"))
elec_consumption <- mutate(elec_consumption,datetime = paste(Date,Time))
y <- data.frame(datetime = as.POSIXlt(NA,""))
y <- strptime(elec_consumption$datetime,"%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
plot(y,elec_consumption$Global_active_power,type="n",xlab="",ylab="Global Active Power")
lines(y,elec_consumption$Global_active_power,type="l")
plot(y,elec_consumption$Voltage,type="n",xlab="datetime",ylab="Voltage")
lines(y,elec_consumption$Voltage,type="l")
plot(y,elec_consumption$Sub_metering_1,type="n",xlab="",ylab="Energy Sub Metering")
lines(y,elec_consumption$Sub_metering_1,type="l")
lines(y,elec_consumption$Sub_metering_2,type="l",col="red")
lines(y,elec_consumption$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_Metering_1","Sub_Metering_2","Sub_Metering_3"),lty=1,col=c("black","red","blue"))
plot(y,elec_consumption$Global_reactive_power,type="n",xlab="datetime",ylab="Global_reactive_power")
lines(y,elec_consumption$Global_reactive_power,type="l")
dev.off()
close(f)