library(DBI)
library(RSQLite)
library(proto)
library(gsubfn)
library(sqldf)
library(tcltk)
f <- file("household_power_consumption.txt")
elec_consumption <- sqldf("select * from f where Date In ('1/2/2007','2/2/2007')", dbname = tempfile(), file.format = list(header = T, row.names = F, sep=";"))
elec_consumption[,1] <- as.Date(elec_consumption[,1],"%d/%m/%Y")
png("plot1.png")
hist(elec_consumption$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()
close(f)