library(DBI)
library(RSQLite)
library(proto)
library(gsubfn)
library(sqldf)
library(tcltk)
library(dplyr)
f <- file("household_power_consumption.txt")
elec_consumption <- sqldf("select * from f where Date In ('1/2/2007','2/2/2007')", dbname = tempfile(), file.format = list(header = T, row.names = F, sep=";"))
elec_consumption <- mutate(elec_consumption,datetime = paste(Date,Time))
y <- data.frame(datetime = as.POSIXlt(NA,""))
y <- strptime(elec_consumption$datetime,"%d/%m/%Y %H:%M:%S")
png("plot2.png")
plot(y,elec_consumption$Global_active_power,type="n",xlab="",ylab="Global Active Power (kilowatts)")
lines(y,elec_consumption$Global_active_power,type="l")
dev.off()
close(f)